create table if not exists public.registration_submissions (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name_en text not null,
  name_cn text,
  date_of_birth date not null,
  nationality text not null,
  email text not null,
  whatsapp text not null,
  wechat text,
  city text not null,
  university text not null,
  programme text not null,
  year_of_study text not null,
  expected_graduation text not null,
  gpa text,
  internship_experience text not null,
  internship_description text,
  licences text[] not null default '{}',
  english_proficiency text not null,
  sectors text[] not null,
  target_location text not null,
  internship_timeline text not null,
  primary_goal text not null,
  programme_interest text not null,
  referral_source text not null,
  contact_preference text not null,
  applicant_type text not null,
  parent_name text,
  parent_relationship text,
  parent_phone text,
  parent_email text,
  student_awareness text,
  privacy_consent boolean not null,
  marketing_consent boolean not null default false,
  accuracy_consent boolean not null
);

alter table public.registration_submissions enable row level security;
